/**
 * [The "BSD license"]
 * Copyright (c) 2016, JGen Notes
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, 
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this list of conditions 
 *    and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions 
 *    and the following disclaimer in the documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS 
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 */
package eu.jgen.beegen.model.mirror.decaration;

public enum AggregateObjectType {

	NOTE, EXIT_STATE_IS, COMMAND_IS, MOVE, SET, IF, CASE_OF, FOR, FOR_EACH, REPEAT_UNTIL, WHILE, CREATE, UPDATE, DELETE, SUMMARIZE_EACH, TRANSFER, UNFILTER, UNHIGHLIGHT, UNMARK_COMMAND, SUMMARIZE, SORT, RETRY, REMOVE_ROW, REFRESH, READ_EACH, PRINTER_TERMINAL, OPEN, OPEN_WINDOW_DIALOG, NEXT, MARK_COMMAND, MAKE, INVOKE, HIGHLIGHT, GET, FILTER, ESCAPE, ENABLE_COMMAND, DISPLAY, DISASSOCIATE, DISABLE_COMMAND, CLOSE_WINDOW, ASSOCIATE, ADD, ABORT, OTHERWISE, ELSE_IF, ELSE, CASE, FUNCTION, ACTION_BLOCK, ACTION_BLOCK_BODY, MAIN, ATTRIBUTE_VIEW, SIMPLE_VIEW, GROUP_VIEW, IMPORTS, EXPORTS, LOCALS, ENTITY_ACTIONS, VIEWS, EVENT, WHEN, READ, WHEN_SUCCESFUL, REMOVE, USE, USE_PROCEDURE_STEP, ACTION_BLOCK_EXTERNAL, ASYNC_USE, IGNORE_ASYNC_RESPONSE, CHECK_ASYNC_RESPONSE, WHEN_AVIALABLE, GET_ASYNC_RESPONSE, STATEMENTS_GROUP

}
